version: '3'

services:
  db:
    container_name: nextcloud_db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    networks:
      - default
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always
    networks:
      - default

  onlyoffice:
    image: onlyoffice/documentserver
    restart: always
    networks:
      - default

  collabora:
    image: collabora/code
    restart: always
    networks:
      - default
    environment:
      # Escape . (i.e. simply prefix all . with \\)
      # Below is sub.example.com
      # Required for trusted access
      - domain=sub\\.example\\.com
      - username=admin
      - password=password
      # Disable if not using ssl
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
      # Enable if not using ssl
      # - "extra_params=--o:ssl.enable=false"

  app:
    container_name: nextcloud_app
    build: ./nextcloud
    restart: always
    networks:
      - default
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
      - onlyoffice
      - collabora

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - default
    ports:
      - 8081:80
    depends_on:
      - db

  web:
    build: ./web
    restart: always
    networks:
      - default
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - app

volumes:
  db:
  nextcloud:

networks:
  default:
